### ISSUE TITLE
Wider "# of words" input box

### ISSUE THREAD

**Issue by ryanbugden** [cjdunn/MM2SpaceCenter#12]
Sometimes the input number exceeds the width of the EditText box → unreadable.

Leaving this here for myself to potentially address when I have time.

**Comment by cjdunn** [comment]
Hmm, I just tried and it's readable up to 99 words. I wouldn't recommend using more than 99 words because it will be very slow in the space center. IIRC space center stops updating after a certain number of character anyway until you click on it or something? So you'd probably hit that limit first. 

Either way, I'm going to close this issue for now.
