### ISSUE TITLE
When opening, open SpaceCenter and MM for current font, if neither is open.

### ISSUE THREAD

**Issue by ryanbugden** [cjdunn/MM2SpaceCenter#33]

**Comment by ryanbugden** [comment]
If you open MM2SpaceCenter, you very probably want both SC and MM open, so this can/should happen automatically IMO, after a check of whether each is open... Some starting code below:

```
from mojo.UI import OpenSpaceCenter
import AppKit

f = CurrentFont()

# open space center
OpenSpaceCenter(f, True)

# open metrics machine instead of printing "there's not a MM open"
## code from Frederik (cleaner way to open MM may be on the way)
mainMenu = AppKit.NSApp().mainMenu()
mmMenu = mainMenu.itemWithTitle_("MetricsMachine")
if mmMenu:
    menu = mmMenu.submenu()
    item = menu.itemWithTitle_("Open Metrics Machine")
    target = item.target()
    target.action_(item)
```

**Comment by cjdunn** [comment]
Thanks for this code, Ryan. I'm actually using this extension with other (unpublished) kerning extensions and I'm finding it equally useful with those. So I'm thinking down the road it will be more generalized, despite the fact that MM is in the name*. I'm thinking of it similar to how Frederik approaches RF, where it doesn't make any assumptions. 

I don't want this extension to start opening other extensions for me. I just want it to display the words in space center if a kerning extension is open which is posting "currentPair" notifications, otherwise it can just hangout and wait until you're kerning again : )    

*I will probably have to think of a new name 🤔

**Comment by ryanbugden** [comment]
Makes sense! Maybe it can just open SC then!
